### ISSUE TITLE
line overflow

### ISSUE THREAD

**Issue by sauloal** [billroy/bitlash#3]
when trying to type the following line:

function startup {pinmode(13,1); pinmode(a0,0); pinmode(a1,1); run toggle13,1000; run readtemp,1000; run readlight,1000; }

by the end I get the message: line overflow

function startup {pinmode(13,1); pinmode(a0,0); pinmode(a1,1); run toggle13,1000; run readtemp,1000; run readlight,1000line overflow

and a bunch of weird characters.

I'm using gnu screen

**Comment by billroy** [comment]
Hello and thanks for the report.  You will run out of room at 120 characters (defined by STRVALSIZE in src/bitlash.h @ 433) but there was a bug in the handling.  I just pushed a change to src/bitlash-cmdline.c that seems to improve matters here.  The new behavior is to beep and discard input if it would overflow the buffer.  (The old behavior threw "line overflow", as you observed.)

Would you pull that file and try it to see if it works for you?

-br

**Comment by billroy** [comment]
Closing this one - the line overflow is fixed.  The new behavior is to beep and discard input when the buffer has no more room.
