### ISSUE TITLE
Cannot 'run' api added functions

### ISSUE THREAD

**Issue by NickShaffner** [billroy/bitlash#38]
given the below sketch, typing 'run hi' from the console complains that it can't find the identifier 'hi'.   Typing 'hi' at the console does the right thing.  If you wrap the 'hi' function inside of a 'function hi wrap { hi; }', running hi wrap works.

numvar hi(void) {
    Serial.println("hello!");
}

void setup() {  
  initBitlash(115200);  
  addBitlashFunction("hi",(bitlash_function)hi);
}

void loop() {
  runBitlash();
}

**Comment by billroy** [comment]
Thanks for your note.  This is a known limitation; the run command only runs functions defined in eeprom.

The workaround is to define a “trampoline function” in eeprom in the usual way to call your user-defined “hi” function.

-br
