### ISSUE TITLE
About reading Arduino local variables from bitlash.

### ISSUE THREAD

**Issue by guaifi** [billroy/bitlash#39]
Hello, I am planning to use bitlash in my home to read sensors remotely.

Some sensors are not than simple as reading a pin, so for example a sensor who works via I2C or SPI... One wire temperature sensors...

So, I can run in arduino a function that communicates with the sensor in the specified protocol, reads the value and stores the result in a local variable. An unsigned int Sensor1Value for ex...

¿¿Do you know any way from remote terminal to say Bitlash that returns me the value of Sensor1Value stored in arduino RAM??

**Comment by billroy** [comment]
Hello and thanks for your note.  

The usual way to handle your requirement is to have the C-based User Function which does the I2C or SPI work return the sensor value as the function’s return value.  Then you can simply call the function and use the result (like “print getsensor1()”).

Another is to use a Bitlash global variable to contain the result.  Your User Function can call “setvar(0, 100)” to set the Bitlash variable ‘a’ to 100, for example, and then it’s available to all Bitlash code.

A third approach would be to use two functions, one to acquire the sensor value and store it in a global unsigned C variable, and another to retrieve and return that value.

Hope that helps, and happy to take followup questions.

-br

**Comment by guaifi** [comment]
Thank you very much for the fast answer!

I would like to try it soon.
