### ISSUE TITLE
Interpret from memory

### ISSUE THREAD

**Issue by shvelo** [billroy/bitlash#4]
Hi, can this used to interpret programs from SDcard?
I mean programmatically, not via the shell.

**Comment by billroy** [comment]
Yes.  Use the example at https://github.com/billroy/bitlash/blob/master/examples/bitlashsd/bitlashsd.pde

Please note the documentation in that file - you need to make a couple edits to the Bitlash source to enable SD card support.

Good luck with your project.

-br

**Comment by shvelo** [comment]
Can I control it without the shell?

**Comment by billroy** [comment]
Yes.  The C API lets you do things from your C program like:

```
doCommand("print 2+2");
```

-br
