### ISSUE TITLE
Cannot use backspace in terminal

### ISSUE THREAD

**Issue by mondalaci** [billroy/bitlash#42]
It'd be very nice to be able to use backspace in the terminal. Currently nothing happens upon pressing backspace. I guess bitlash should echo backspace towards the client and shorten the command buffer by one character.

 A Pinoccio user :)

**Comment by matthijskooijman** [comment]
@mondalaci, I actually think what you suggest is implemented already, both in regular bitlash as well as in the Pinoccio version (which uses its own input-processing loop, here: https://github.com/Pinoccio/library-pinoccio/blob/master/src/Shell.cpp#L2696-L2705).

Could you clarify what code you're running exactly?

Perhaps your terminal isn't sending regular backspace characters? What terminal are you using?

**Comment by mondalaci** [comment]
@matthijskooijman I'm using GNU screen on Linux and having the latest firmware that has been fetched by HQ.

**Comment by matthijskooijman** [comment]
Hmm, seems this is something specific with screen - it doesn't work for me either when using screen. I suspect screen is sending different bytes for backspace, I'll have a closer look soon. In the meanwhile, you could try using a different terminal (I use minicom).

**Comment by mondalaci** [comment]
Minicom indeed works! I'd also be interested to figure out what's going on
with screen and how can I make it work properly in this respect. Thanks!

On Mon, Jan 19, 2015 at 12:39 PM, Matthijs Kooijman <
notifications@github.com> wrote:

> Hmm, seems this is something specific with screen - it doesn't work for me
> either when using screen. I suspect screen is sending different bytes for
> backspace, I'll have a closer look soon. In the meanwhile, you could try
> using a different terminal (I use minicom).
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/billroy/bitlash/issues/42#issuecomment-70480698.

## 

László Monda https://monda.hu

**Comment by matthijskooijman** [comment]
Turns out that screen sends a delete (0x7f) instead of backspace. I think this is a common problem with terminals, I remember BSD vs Linux to also suffer from problems like this. I've modified the pinoccio code to [handle both as backspace](https://github.com/Pinoccio/library-pinoccio/pull/226). It turns out that [bitlash already does this as well](https://github.com/billroy/bitlash/blob/master/src/bitlash-cmdline.c#L165), should have looked better at bill's code when writing our own :-)

In any case, I think this ticket can be closed.

**Comment by mondalaci** [comment]
@matthijskooijman Mad props to you for figuring out and fixing legacy bullshit like this! :)

Closing ticket.

**Comment by billroy** [comment]
Thanks for following up, Matthijs.

FYI/FWIW, here's what I use to avoid the issues with screen and minicom.  I wrote a little terminal emulator named "bloader.js" that you can install via npm.  Source here: https://github.com/billroy/bloader.js

**Comment by ticpu** [comment]
For a CLI tool there is also picocom which has less options and a couple
useful shortcuts. In between screen and minicom.
